config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :students, except: %i[index new edit] do
    resources :lessons, only: %i[create update destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :lessons, dependent: :destroy
  belongs_to :user

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  after_save :geocode, if: :will_save_change_to_address?

  before_save do
    url = "https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyD3ij-HtJdr5qgksBH5zRNiS7Rfk0IZe7Q&latlng=#{self.latitude},#{self.longitude}&sensor=true"
    response = RestClient.get(url)
    self.formatted_address = JSON.parse(response)['results'][0]['formatted_address']
  end

  def promote_to_most_recent
    self.update(tag: Student.find_most_recent.tag + 1)
  end

  def self.find_most_recent
    tags = Student.all.map { |student| student.tag }.uniq.sort
    tags.length == 1 ? Student.first : Student.find_by(tag: tags.last)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :students
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :find_lesson, only: [:show, :update, :destroy]

  def show
  end

  def create
    @student = Student.find(params[:student_id])
    @lesson = Lesson.new(lesson_params)
    @lesson.student = @student
    @lesson.save
    redirect_to student_path(@student)
  end

  def update
    @lesson.update(lesson_params)
    redirect_to student_path(Student.find(params[:student_id]))
  end

  def destroy
    @student = Student.find(params[:student_id])
    @lesson.destroy
    redirect_to student_path(@student)
  end

  private

  def lesson_params
    params.require(:lesson).permit(:theme, :description, :date)
  end

  def find_lesson
    @lesson = Lesson.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    if user_signed_in?
      if !current_user.students.count.zero?
        @student = current_user.students.first
      end
    end
    @newStudent = Student.new
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :find_student, only: [:show, :update, :destroy]

  def show
    @lessons = @student.lessons.sort_by { |lesson| lesson.date }
    @newLesson = Lesson.new
    @newStudent = Student.new
    @markers = [
      {
        lat: @student.latitude,
        lng: @student.longitude
      }
    ]
    @student.promote_to_most_recent
  end

  def create
    @student = Student.new(student_params)
    @student.user = current_user
    @student.tag = 0
    @student.save
    redirect_to student_path(@student)
  end

  def update
    @student.update(student_params)
    redirect_to student_path(@student)
  end

  def destroy
    @student.destroy
    if current_user.students.count.zero?
      redirect_to root_path
    else
      redirect_to student_path(Student.first)
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :address, :situation)
  end

  def find_student
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tutor Planner</title>
    <%= favicon_link_tag asset_path('logo_transparent.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="spacer"></div>
    <%= render 'shared/flashes' %>
    <% unless params['controller'] == 'pages' %>
      <div class="container">
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key="+ENV['GOOGLE_API']+"&callback=initMap" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/lessons/edit.html.erb
<%= simple_form_for [@student, @lesson] do |f| %>
  <%= f.input :theme %>
  <%= f.input :description %>
  <%= f.input :date %>
  <%= f.submit "Save lesson", class: "btn btn-primary" %>
<% end %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=a53f6ccb2fccd80ae7f6c6af8f289319&auto=format&fit=crop&w=500&q=60');">
  <div class="banner-content">
    <h1>Tutor Planner</h1>
    <p>Plan your lessons and travel. Done</p>
    <% if user_signed_in? %>
      <% if current_user.students.count.zero? %>
        <div class="btn btn-danger btn-lg" data-toggle="modal" data-target="#newStudentModal">
          Add a student
        </div>
      <% else %>
        <%= link_to student_path(@student) do %>
          <div class="btn btn-danger btn-lg">Review your students</div>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to new_user_registration_path do %>
        <div class="btn btn-danger btn-lg">Sign up</div>
      <% end %>
    <% end %>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="newStudentModal" tabindex="-1" role="dialog" aria-labelledby="newStudentLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title highlight-red" id="newStudentLabel">Add new student</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @newStudent do |f| %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :situation %>
          <%= f.submit "Save new student", class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<%# if notice %>
<!--   <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%#= notice %>
  </div>
 --><%# end %>
<%# if alert %>
<!--   <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%#= alert %>
  </div>
 --><%# end %>

app/views/shared/_lesson.html.erb
<div class="lesson">
  <div class="lesson-category">
    <p><%= lesson.theme %></p>
  </div>
  <div class="lesson-date">
    <p><%= lesson.date.strftime("%a %b") + " " + lesson.date.day.ordinalize %></p>
  </div>
  <div class="lesson-description">
    <p class="opacity-5 highlight-red"><%= lesson.description %><p>
  </div>
  <div class="lesson-buttons">
    <ul class="list-inline">
      <li class="lesson-button">
        <p><i class="far fa-edit highlight-red" data-toggle="modal" data-target="#editLesson<%= lesson.id %>"></i></p>
      </li>
      <li class="lesson-button">
        <%= link_to student_lesson_path(student, lesson), method: :delete do %>
          <p><i class="far fa-trash-alt"></i></p>
        <% end %>
      </li>
    </ul>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="editLesson<%= lesson.id %>" tabindex="-1" role="dialog" aria-labelledby="editLessonLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title highlight-red" id="editLessonLabel">Edit lesson for <%= student.name %></h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for [student, lesson] do |f| %>
          <%= f.input :theme %>
          <%= f.input :description %>
          <%= f.input :date, input_html: {class: "datepicker"} %>
          <%= f.submit "Save changes", class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-app">
  <div class="navbar-center">
    <div class="logo-left">
      Tutor
    </div>
    <%= link_to root_path do %>
      <%= image_tag "logo_transparent.png", alt: "logo", class: "logo-image navbar-link" %>
    <% end %>
    <div class="logo-right">
      Planner
    </div>
  </div>
  <% if user_signed_in? %>
    <!-- Left Navigation -->
    <% if params['controller'] != 'pages' %>
      <div class="navbar-left">
        <p class="navbar-link" data-toggle="modal" data-target="#newStudentModal">New student</p>
      </div>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-right">
      <% if params['action'] == 'show'%>
        <i class="navbar-link button-student far fa-trash-alt" data-toggle="modal" data-target="#deleteStudentModel"></i>
        <i class="navbar-link button-student far fa-edit" data-toggle="modal" data-target="#editStudentModel"></i>
        <div class="dropdown">
          <div class="navbar-link navbar-item dropdown-toggle" id="navbar-student-menu"
          data-toggle="dropdown"><%= @student.name %> <i class="fa fa-sort"></i></div>
          <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu" style="margin-top: 22px !important;">
            <% current_user.students.sort_by{|s| s.tag }.reverse.each do |student| %>
            <li>
              <%= link_to student.name, student_path(student), class: "navbar-link" %>
            </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <% if user_signed_in? %>
      <!-- Avatar with dropdown menu -->
        <div class="navbar-item">
          <div class="dropdown">
            <p class="fas fa-user-tie fa-2x" class="avatar dropdown-toggle" id="navbar-profile-menu"
            data-toggle="dropdown" ></p>
            <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu" style="margin-top: 16px !important;">
              <li>
                <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="navbar-left">
      <% if params['controller'] == 'devise/sessions' && params['action'] == 'new' %>
        <%= link_to "Sign up", new_user_registration_path %>
      <% else %>
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    </div>
  <% end %>
</div>

<% if user_signed_in? %>
  <% if params['controller'] != 'pages' %>
    <!-- Modal -->
    <div class="modal fade" id="newStudentModal" tabindex="-1" role="dialog" aria-labelledby="newStudentLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title highlight-red" id="newStudentLabel">Add new student</h4>
          </div>
          <div class="modal-body">
            <%= simple_form_for @newStudent do |f| %>
              <%= f.input :name %>
              <%= f.input :address %>
              <%= f.input :situation %>
              <%= f.submit "Save new student", class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% if params['controller'] == 'students' && params['action'] == 'show' %>
    <!-- Edit student modal -->
    <div class="modal fade" id="editStudentModel" tabindex="-1" role="dialog" aria-labelledby="editStudentLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="editStudentLabel">Edit <%= @student.name %>'s details</h4>
          </div>
          <div class="modal-body">
            <%= simple_form_for @student do |f| %>
              <%= f.input :name %>
              <%= f.input :address %>
              <%= f.input :situation %>
              <%= f.submit "Save student", class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <!-- Delete student modal -->
    <div class="modal fade" id="deleteStudentModel" tabindex="-1" role="dialog" aria-labelledby="deleteStudentLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="deleteStudentLabel">Are you sure you want to delete <%= @student.name %>?</h4>
          </div>
          <div class="modal-body">
            <p class="no-margin-below highlight-red align-center">
              This action is irreversible!
            </p>
          </div>
          <div class="modal-footer">
            <%= link_to "Delete", student_path, method: :delete, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/students/show.html.erb
<div class="row">
  <div class="col-xs-5">
    <h1>
      Student info
    </h1>
    <div id="left">
      <div class="student-details">
        <p class="student-situation"><%= @student.situation %></p>
        <p class="student-address"><%= @student.formatted_address %></p>
      </div>
      <div id="map" data-markers="<%= @markers.to_json %>">
      </div>
    </div>
  </div>
  <div class="col-xs-7">
    <h1>
      Lessons
      <i class="new-lesson fas fa-plus-circle fa-sm" data-toggle="modal" data-target="#newLesson"></i>
    </h1>
    <div id="right">
      <% if @lessons.count.zero? %>
        <div class="lesson">
          <div class="new-lesson-prompt">
            No lessons yet...
          </div>
        </div>
      <% else %>
        <% @lessons.each do |lesson| %>
          <%= render partial: "shared/lesson", locals: { student: @student, lesson: lesson } %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<!-- modal -->
<div class="modal fade" id="newLesson" tabindex="-1" role="dialog" aria-labelledby="newLessonLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title highlight-red" id="newLessonLabel">New lesson for <%= @student.name %></h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@student, @newLesson] do |f| %>
          <%= f.input :theme %>
          <%= f.input :description %>
          <%= f.input :date %>
          <%= f.submit "Save new lesson", class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
</div>